name: Build develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package --file rsvp-service/pom.xml

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        run: mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph -f rsvp-service/pom.xml

      # Set up Node.js for npm build
      - name: Set up Node.js
        uses: actions/setup-node@v3
        # Specify the Node.js version required for the React project
        with:
          node-version: '20'

      - name: Complete lint check
        working-directory: rsvp-ui
        run: |
          npm install
          npm run lint

      # Install dependencies, build, and test npm project
      - name: Install and Build npm Project
        working-directory: rsvp-ui
        run: |
          npm install
          npm run build

      # Comment until tests are implemented
      # - name: Run Tests for npm Project
      #   working-directory: rsvp-ui
      #   run: npm test
